import type { Metadata } from "next";
import { Public_Sans } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import {
  SidebarProvider,
  Sidebar,
  SidebarInset,
  SidebarHeader,
  SidebarContent,
  SidebarFooter,
} from "@/components/ui/sidebar";
import { NavLogo } from "@/components/custom/nav-logo";
import { NavMenu } from "@/components/custom/nav-menu";
import { ThemeToggle } from "@/components/custom/theme-toggle";
import { Toaster } from "@/components/ui/sonner";

const publicSans = Public_Sans({
  variable: "--font-public-sans",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Agent builder prototype",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${publicSans.variable} antialiased h-screen overflow-hidden`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange={false}
          storageKey="prototyping-theme"
        >
          <SidebarProvider>
            <Sidebar collapsible="icon" className="bg-bg1">
              <SidebarHeader>
                <NavLogo />
              </SidebarHeader>
              <SidebarContent className="px-3 py-2">
                <NavMenu />
              </SidebarContent>
              <SidebarFooter className="mt-auto p-4">
                <ThemeToggle />
              </SidebarFooter>
            </Sidebar>
            <SidebarInset className="h-screen overflow-hidden">
              {children}
            </SidebarInset>
          </SidebarProvider>
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
